# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewMe', '0002_auto_20171111_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='input_text',
            field=models.CharField(default='', max_length=100000),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_text',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
