# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewMe', '0019_remove_feedback_input_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='input_text',
            field=models.CharField(default='bob', max_length=100000),
        ),
    ]
