# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewMe', '0022_speechrec'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.CharField(default='Hello', max_length=100000)),
                ('conclusion', models.CharField(default='Goodbye', max_length=100000)),
                ('question_1', models.CharField(default="What's your greatest weakness?", max_length=100000)),
                ('question_2', models.CharField(default='Describe a team you showed leadership.', max_length=100000)),
                ('question_3', models.CharField(default="What's your work-style?", max_length=100000)),
            ],
        ),
    ]
