# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewMe', '0023_interview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='intro',
            field=models.CharField(default="Hello and welcome. Let's get started. ", max_length=100000),
        ),
    ]
